### PR TITLE
add noop legacy output for nteract-scrapbook

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- this adds multiple `outputs`, with an `nteract-scrapbook` that exists only to depend on `scrapbook` at the exact version (though build numbers won't be consulted)
- @mseal if this is a **terrible idea**, please let me know... dagster might be the only downstream, so maybe this isn't a big deal, but renaming is always awkward

### CODE REVIEW

**Review by MSeal — APPROVED** [review]

**Review by MSeal — COMMENTED** [review]
Hmm actually on second thought -- what's the motivation here for the change?

**Comment by bollwyvl** [comment]
https://github.com/conda-forge/dagster-feedstock/pull/106

(the reason i am helping maintain this package in the first place :tada: )

**Comment by bollwyvl** [comment]
Basically, I want a smooth, tested upgrade path to the 0.5 line for dagster installs

**Comment by MSeal** [comment]
More specifically why make a hollow reference, over changing the downstream to use the new name? We version separated the package name change so libraries could swap over to the new minor version without disrupting pulls from the old version name.

Oh did I just mess up the name change the first time around on the feedstock? Should we just drop the `nteract-scrapbook` output? Apologies for catching up on how feedstocks work again...

**Comment by bollwyvl** [comment]
> changing the downstream to use the new name?

I haven't dug into the complexity behind what's running under the hood `papermill` versions, etc. But specifically, in my case, with a downstream like `dagster` which needs to work correctly next to `airflow` + `graphl` + `grpc` + dog, environments can become unsolveable (e.g. that shiny new m1 doesn't have `<old version> on <old python> of <transient dependency>`). I'd rather find out about that _now_, while trying to package, rather than when someone can't install the downstream with "fancy new feature x," because they are stuck on `grpcio X.Y.Z`

**Comment by bollwyvl** [comment]
> mess up the name change the first time around on the feedstock?

Nope, what you did is exactly right, it just means that no downstreams will ever pull new versions.... and installing _both_, next to each other, would break the world.

**Comment by MSeal** [comment]
If it makes the world simpler for you, I'm OK merging. I do dislike dual package name patterns because it's confusing and upstream packages should really be able to control their versions and naming without indefinitely maintaining older patterns. But I'm less familiar with convention here with conda feedstocks so I'll defer to you. Just wanted to bring it up as what I'd see as an anti-pattern and maintenance concern down the road.

**Comment by bollwyvl** [comment]
Indeed, my world is simpler now.

**Pull request merged**
